export const TipMessages = [
  "Depois de beber várias doses, não é recomendado comer pó de cerâmica.",
  "Água entre os drinks ajuda o fígado a te perdoar.",
  "Evite mandar mensagem pro ex: a ressaca emocional dura mais que a física.",
  "Se dançar em cima da mesa, escolha uma que aguente o tranco.",
  "Cuidado com drinks azuis: eles sempre parecem inofensivos.",
  "Se você começou a filosofar demais, talvez seja hora de um copo de água.",
  "Não aceite conselhos de alguém que acabou de perder no truco.",
  "Beber e jogar Jenga emocional não combinam.",
  "O bartender é seu amigo, mas não seu terapeuta.",
  "A pizza de madrugada é uma promessa que vale cumprir.",
  "Se você esqueceu onde deixou o copo, talvez seja hora de parar.",
  "Dance como se ninguém estivesse filmando (mas eles provavelmente estão).",
  "Cantar evidências alto demais tem consequências sociais.",
  "O shot que parece fácil agora, pode ser difícil amanhã.",
  "Se o chão parece confortável, é hora de ir pra casa.",
  "Quem mistura bebida, mistura problema. Escolha seu veneno com sabedoria.",
  "Se está rindo demais do gelo no copo, vá devagar.",
  "Nem todo mundo que te oferece um drink tem boas intenções.",
  "Evite debates existenciais depois do terceiro copo.",
  "O Uber custa menos que o arrependimento.",
];
